spec:
  template:
    spec:
      containers:
      - env:
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent-udp-hrupp1.8a09.starter-us-east-2.openshiftapps.com
        - name: JAEGER_AGENT_PORT
          value: 6831
        - name: JAEGER_SERVICE_NAME
          value: XXX-TODO
        - name: JAEGER_HTTP_QUERY_URL
          value: http://jaeger-agent-hrupp1.8a09.starter-us-east-2.openshiftapps.com/api/traces  
        resources:
            limits:
              cpu: "40m"
              memory: "256Mi"
            requests:
              cpu: "29m"
              memory: "180Mi"