spec:
  template:
    spec:
      containers:
      - env:
        - name: JAEGER_AGENT_HOST
          value: localhost
        - name: JAEGER_AGENT_PORT
          value: 8080
        - name: JAEGER_SERVICE_NAME
          value: XXX-TODO
